// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package toolspec

type EchoSchemaJson struct {
	// The message to echo back
	Msg string `json:"msg" yaml:"msg" mapstructure:"msg"`
}
